# Help: https://code-maze.com/mysql-aspnetcore-docker-compose/

version: '3.0'

services:
  app:
    image: 192.168.178.21:5000/dotnetcore-vue-template
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8080:80"
    healthcheck:
      test: curl --silent --fail http://localhost:80/health || exit 1
      interval: 15s
      timeout: 15s
      retries: 3

# uses custom registry on 192.168.178.21:5000
# https://linuxhint.com/setup_own_docker_image_repository/
# docker for desktop edge was needed to edit insecure-registries